import '../models/product.dart';

/// 목업 카탈로그 (실제 DB 연동 전까지 MockProductRepository가 사용).
const List<Product> kSampleCatalog = [
  Product(
    id: 'p1',
    brand: '무드랩',
    name: '레티놀 0.1% 나이트 세럼',
    category: '세럼',
    ingredients: ['정제수', '스쿠알란', '레티놀 0.1%', '세라마이드NP', '토코페롤', '글리세린'],
    barcode: '8800000000011',
  ),
  Product(
    id: 'p2',
    brand: '무드랩',
    name: '레티날 0.05% 리뉴얼 크림',
    category: '크림',
    ingredients: ['정제수', '레티날 0.05%', '세라마이드NP', '판테놀', '시어버터'],
    barcode: '8800000000028',
  ),
  Product(
    id: 'p3',
    brand: '클리어데이',
    name: 'AHA 7% 브라이트닝 토너',
    category: '토너',
    ingredients: ['정제수', '글리콜릭애씨드 7%', '판테놀', '알란토인', '부틸렌글라이콜'],
    barcode: '8800000000035',
  ),
  Product(
    id: 'p4',
    brand: '클리어데이',
    name: 'BHA 2% 포어 클리어 토너',
    category: '토너',
    ingredients: ['정제수', '살리실산 2%', '녹차추출물', '판테놀'],
    barcode: '8800000000042',
  ),
  Product(
    id: 'p5',
    brand: '클리어데이',
    name: 'PHA 5% 데일리 필링 패드',
    category: '토너',
    ingredients: ['정제수', '글루코노락톤 5%', '판테놀', '알로에베라잎즙'],
    barcode: '8800000000059',
  ),
  Product(
    id: 'p6',
    brand: '라보에센',
    name: '퓨어 비타민C 15 앰플',
    category: '에센스·앰플',
    ingredients: ['정제수', '아스코빅애씨드 15%', '비타민E', '페룰릭애씨드'],
    barcode: '8800000000066',
  ),
  Product(
    id: 'p7',
    brand: '라보에센',
    name: '나이아신아마이드 10 세럼',
    category: '세럼',
    ingredients: ['정제수', '나이아신아마이드 10%', '징크PCA', '글리세린'],
    barcode: '8800000000073',
  ),
  Product(
    id: 'p8',
    brand: '라보에센',
    name: '비타민C 브라이트닝 토너',
    category: '토너',
    ingredients: ['정제수', '아스코빅애씨드 5%', '나이아신아마이드', '베타인'],
    barcode: '8800000000080',
  ),
  Product(
    id: 'p9',
    brand: '그린노트',
    name: '시카 배리어 리페어 크림',
    category: '크림',
    ingredients: ['정제수', '병풀추출물', '세라마이드NP', '마데카소사이드', '판테놀'],
    barcode: '8800000000097',
  ),
  Product(
    id: 'p10',
    brand: '그린노트',
    name: '병풀 진정 토너',
    category: '토너',
    ingredients: ['병풀추출물 70%', '마데카소사이드', '판테놀', '알란토인'],
    barcode: '8800000000103',
  ),
  Product(
    id: 'p11',
    brand: '워터풀',
    name: '히알루론 딥 수분 토너',
    category: '토너',
    ingredients: ['정제수', '히알루론산', '판테놀', '베타인'],
    barcode: '8800000000110',
  ),
  Product(
    id: 'p12',
    brand: '워터풀',
    name: '히알루론 수분 앰플',
    category: '에센스·앰플',
    ingredients: ['정제수', '히알루론산', '트레할로스', '베타인'],
    barcode: '8800000000127',
  ),
  Product(
    id: 'p13',
    brand: '바리에',
    name: '세라마이드 장벽 수분크림',
    category: '크림',
    ingredients: ['정제수', '세라마이드NP', '콜레스테롤', '스쿠알란'],
    barcode: '8800000000134',
  ),
  Product(
    id: 'p14',
    brand: '바리에',
    name: '판테놀 5% 리페어 세럼',
    category: '세럼',
    ingredients: ['정제수', '판테놀 5%', '마데카소사이드', '글리세린'],
    barcode: '8800000000141',
  ),
  Product(
    id: 'p15',
    brand: '선리',
    name: '마일드 무기자차 선크림 SPF50+',
    category: '선크림',
    ingredients: ['정제수', '징크옥사이드', '나이아신아마이드', '알로에베라'],
    barcode: '8800000000158',
  ),
  Product(
    id: 'p16',
    brand: '선리',
    name: '워터리 선에센스 SPF50+ PA++++',
    category: '선크림',
    ingredients: ['정제수', '에틸헥실메톡시신나메이트', '히알루론산', '글리세린'],
    barcode: '8800000000165',
  ),
  Product(
    id: 'p17',
    brand: '픽스온',
    name: '톤업 커버 쿠션 SPF35',
    category: '메이크업',
    ingredients: ['티타늄디옥사이드', '나이아신아마이드', '다이메티콘'],
    barcode: '8800000000172',
  ),
  Product(
    id: 'p18',
    brand: '아크랩',
    name: '벤조일 2.5% 스팟 젤',
    category: '기타',
    ingredients: ['정제수', '벤조일퍼옥사이드 2.5%', '글리세린'],
    barcode: '8800000000189',
  ),
  Product(
    id: 'p19',
    brand: '유스랩',
    name: '구리펩타이드 탄력 세럼',
    category: '세럼',
    ingredients: ['정제수', '구리펩타이드', '아데노신', '히알루론산'],
    barcode: '8800000000196',
  ),
  Product(
    id: 'p20',
    brand: '아이브라이트',
    name: '펩타이드 카페인 아이크림',
    category: '아이크림',
    ingredients: ['정제수', '펩타이드', '카페인', '세라마이드NP'],
    barcode: '8800000000202',
  ),
];

/// 처음 로그인했을 때 보여 줄 내 화장대 예시 제품
const List<Product> kSampleVanity = [
  Product(
    id: 'v1',
    brand: '무드랩',
    name: '레티놀 0.1% 나이트 세럼',
    category: '세럼',
    registeredAt: '2026.09.21',
    ingredients: ['레티놀 0.1%', '세라마이드NP', '스쿠알란', '토코페롤'],
  ),
  Product(
    id: 'v2',
    brand: '클리어데이',
    name: 'AHA 7% 브라이트닝 토너',
    category: '토너',
    registeredAt: '2026.09.18',
    ingredients: ['글리콜릭애씨드 7%', '판테놀', '알란토인'],
  ),
  Product(
    id: 'v3',
    brand: '그린노트',
    name: '시카 배리어 리페어 크림',
    category: '크림',
    registeredAt: '2026.09.12',
    ingredients: ['병풀추출물', '세라마이드NP', '마데카소사이드', '판테놀'],
  ),
  Product(
    id: 'v4',
    brand: '선리',
    name: '마일드 무기자차 선크림 SPF50+',
    category: '선크림',
    registeredAt: '2026.09.05',
    ingredients: ['징크옥사이드', '나이아신아마이드', '알로에베라'],
  ),
  Product(
    id: 'v5',
    brand: '라보에센',
    name: '퓨어 비타민C 15 세럼',
    category: '세럼',
    registeredAt: '2026.08.29',
    ingredients: ['아스코빅애씨드 15%', '비타민E', '페룰릭애씨드'],
  ),
  Product(id: 'v6', brand: '워터풀', name: '히알루론 딥 수분 토너', category: '토너', registeredAt: '2026.08.17', ingredients: ['히알루론산', '판테놀', '베타인']),
  Product(
    id: 'v7',
    brand: '바리에',
    name: '세라마이드 장벽 수분크림',
    category: '크림',
    registeredAt: '2026.08.02',
    ingredients: ['세라마이드NP', '콜레스테롤', '스쿠알란'],
  ),
  Product(
    id: 'v8',
    brand: '클리어데이',
    name: 'BHA 2% 포어 클리어 토너',
    category: '토너',
    registeredAt: '2026.07.24',
    ingredients: ['살리실산 2%', '녹차추출물', '판테놀'],
  ),
];

/// "샘플 5단계 루틴" 버튼이 채우는 제품
const List<String> kSampleRoutineIds = ['p3', 'p6', 'p1', 'p9', 'p15'];
